apiVersion: v1
kind: Service
metadata:
  name: banking-app-service
spec:
  selector:
    app: banking-app-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
